### ISSUE TITLE
[spawn_pedsim_agents]: service not available, waiting again...

### ISSUE THREAD

**Issue by atinfinity** [stephenadhi/pedsim_ros#2]
@stephenadhi I tried to use `pedsim_ros` on ROS 2 Humble.
At first, I installed `ros-humble-desktop-full`. And, I installed `pedsim_ros`.

```shell
sudo apt install ros-humble-gazebo-ros ros-humble-nav2-bringup
mkdir -p dev_ws/src
cd dev_ws/src
git clone https://github.com/stephenadhi/pedsim_ros.git
cd ..
colcon build
source install/setup.bash 
```

And, I executed the following command according to [README.md](https://github.com/stephenadhi/pedsim_ros/blob/09cf5d40e28636165f90050d63c0c5eb52641387/README.md#sample-usage-with-turtlebot3).

```shell
ros2 launch pedsim_gazebo_plugin gazebo_tb3_house_demo_launch.py
```

But, I could not launch this demo. And, the following message was displayed. Could you give me your comment?

```shell
[spawn_pedsim_agents]: service not available, waiting again...
```

**Comment by atinfinity** [comment]
I executed `source /usr/share/gazebo/setup.sh`.

```shell
source /usr/share/gazebo/setup.sh
ros2 launch pedsim_gazebo_plugin gazebo_tb3_house_demo_launch.py
```

When I run this command, the error message changed.

```shell
[pedsim_simulator-5] [INFO] [1697557622.976630020] [pedsim_simulator]: Using default queue size of 10 for publisher queues... 
[spawn_pedsim_agents-4] [WARN] [1697557624.172675888] [spawn_pedsim_agents]: Failed to spawn entity: 3
[spawn_pedsim_agents-4] [WARN] [1697557624.185162684] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.193551533] [spawn_pedsim_agents]: Failed to spawn entity: 3
[spawn_pedsim_agents-4] [WARN] [1697557624.201229360] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.209447638] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.220225336] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.225579223] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.233726049] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.242300653] [spawn_pedsim_agents]: Failed to spawn entity: 2
[spawn_pedsim_agents-4] [WARN] [1697557624.254759836] [spawn_pedsim_agents]: Failed to spawn entity: 2
```

**Comment by atinfinity** [comment]
I investigated this. I executed the following command.

```shell
export TURTLEBOT3_MODEL=waffle
ros2 launch turtlebot3_gazebo turtlebot3_dqn_stage1.launch.py
ros2 run pedsim_gazebo_plugin spawn_single_agent.py
```

As a result, an agent was spawned in world.

![image](https://github.com/stephenadhi/pedsim_ros/assets/2630323/c1bbbe95-8de4-431a-a63b-012d824722d5)

So, I think that there is problem in `gazebo_tb3_house_demo_launch.py`.

**Comment by stephenadhi** [comment]
Hi, thank you for the issue submission. First of all, the launch file works without error in my system and you can ignore the spawn entity warnings. If you provide the full error log I could maybe help with your issue.

```
source /usr/share/gazebo/setup.sh
export TURTLEBOT3_MODEL=waffle
ros2 launch pedsim_gazebo_plugin gazebo_tb3_house_demo_launch.py
```

After running the above commands you should see something like this:

![image](https://github.com/stephenadhi/pedsim_ros/assets/32376039/4a9cf0b3-901f-462d-b40c-17f0a72ae688)

You should refrain from using the Python script since from my experience it has issues when dealing with multiple agents. That is why I migrated the gazebo spawner to cpp. Assuming the pedsim simulator is running already, you can spawn the agents in gazebo by:

```
ros2 run pedsim_gazebo_plugin spawn_pedsim_agents
```

**Comment by atinfinity** [comment]
@stephenadhi Thank you for your advice! At first time, I need to wait a few minutes for the preparation of Gazebo.

![image](https://github.com/stephenadhi/pedsim_ros/assets/2630323/2a8738e2-585a-45b9-8198-cdbc4a5e920d)
